--!strict
-- Crystal Dimension: exactly 7 standard blocks and 7 standard turrets.
local ItemConfigurations = {

	-- BLOCKS
	QuartzBlock = { DisplayName = "Quartz Block", Type = "Blocks", Price = 11180, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_QUARTZBLOCK_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_QUARTZBLOCK_PRODUCT_ID", Unlimited = false, Chance = 100, StockAmount = { Min = 1, Max = 7 }, Health = 300000 },
	AmethystBlock = { DisplayName = "Amethyst Block", Type = "Blocks", Price = 22919, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_AMETHYSTBLOCK_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_AMETHYSTBLOCK_PRODUCT_ID", Unlimited = false, Chance = 80, StockAmount = { Min = 1, Max = 7 }, Health = 510000 },
	SapphireBlock = { DisplayName = "Sapphire Block", Type = "Blocks", Price = 46983, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_SAPPHIREBLOCK_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_SAPPHIREBLOCK_PRODUCT_ID", Unlimited = false, Chance = 60, StockAmount = { Min = 1, Max = 7 }, Health = 720000 },
	PrismaticBlock = { DisplayName = "Prismatic Block", Type = "Blocks", Price = 96315, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_PRISMATICBLOCK_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_PRISMATICBLOCK_PRODUCT_ID", Unlimited = false, Chance = 40, StockAmount = { Min = 1, Max = 7 }, Health = 930000 },
	ResonantBlock = { DisplayName = "Resonant Block", Type = "Blocks", Price = 197446, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_RESONANTBLOCK_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_RESONANTBLOCK_PRODUCT_ID", Unlimited = false, Chance = 30, StockAmount = { Min = 1, Max = 7 }, Health = 1140000 },
	DimensionLatticeBlock = { DisplayName = "Dimension Lattice Block", Type = "Blocks", Price = 404765, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_DIMENSIONLATTICEBLOCK_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_DIMENSIONLATTICEBLOCK_PRODUCT_ID", Unlimited = false, Chance = 20, StockAmount = { Min = 1, Max = 7 }, Health = 1350000 },
	CrystalCoreBastion = { DisplayName = "Crystal Core Bastion", Type = "Blocks", Price = 829768, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_CRYSTALCOREBASTION_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_CRYSTALCOREBASTION_PRODUCT_ID", Unlimited = false, Chance = 10, StockAmount = { Min = 1, Max = 7 }, Health = 1560000 },

	-- TURRETS
	Shardcaster = { DisplayName = "Shardcaster", Type = "Turrets", Price = 89438, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_SHARDCASTER_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_SHARDCASTER_PRODUCT_ID", Unlimited = false, Chance = 100, StockAmount = { Min = 1, Max = 4 }, Damage = 240000, Range = 30, FireRate = 2, Health = 480000 },
	QuartzRepeater = { DisplayName = "Quartz Repeater", Type = "Turrets", Price = 192292, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_QUARTZREPEATER_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_QUARTZREPEATER_PRODUCT_ID", Unlimited = false, Chance = 80, StockAmount = { Min = 1, Max = 4 }, Damage = 480000, Range = 32.5, FireRate = 1.88, Health = 744000 },
	PrismSplitter = { DisplayName = "Prism Splitter", Type = "Turrets", Price = 413429, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_PRISMSPLITTER_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_PRISMSPLITTER_PRODUCT_ID", Unlimited = false, Chance = 60, StockAmount = { Min = 1, Max = 4 }, Damage = 840000, Range = 35, FireRate = 1.76, Health = 1008000 },
	ResonanceCannon = { DisplayName = "Resonance Cannon", Type = "Turrets", Price = 888872, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_RESONANCECANNON_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_RESONANCECANNON_PRODUCT_ID", Unlimited = false, Chance = 40, StockAmount = { Min = 1, Max = 4 }, Damage = 1200000, Range = 37.5, FireRate = 1.64, Health = 1272000 },
	LatticeRay = { DisplayName = "Lattice Ray", Type = "Turrets", Price = 1911074, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_LATTICERAY_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_LATTICERAY_PRODUCT_ID", Unlimited = false, Chance = 30, StockAmount = { Min = 1, Max = 4 }, Damage = 1920000, Range = 40, FireRate = 1.52, Health = 1536000 },
	DimensionPiercer = { DisplayName = "Dimension Piercer", Type = "Turrets", Price = 4108809, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_DIMENSIONPIERCER_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_DIMENSIONPIERCER_PRODUCT_ID", Unlimited = false, Chance = 20, StockAmount = { Min = 1, Max = 4 }, Damage = 3360000, Range = 42.5, FireRate = 1.4, Health = 1800000 },
	SingularityPrism = { DisplayName = "Singularity Prism", Type = "Turrets", Price = 8833940, ImageId = "rbxassetid://REPLACE_06_CRYSTAL_DIMENSION_SINGULARITYPRISM_IMAGE_ID", ProductID = "REPLACE_06_CRYSTAL_DIMENSION_SINGULARITYPRISM_PRODUCT_ID", Unlimited = false, Chance = 10, StockAmount = { Min = 1, Max = 4 }, Damage = 4800000, Range = 45, FireRate = 1.28, Health = 2064000 },
}

return ItemConfigurations
